version: '3.9'
services:
  app:
    container_name: docker-node-mongo
    build: .
    ports:
      - '3000:3000'
    external_links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27018:27017'
